### ISSUE TITLE
Module suddenly stop working

### ISSUE THREAD

**Issue by Nikolara97** [andrew-s-taylor/WindowsAutopilotInfo#20]
Hi Andrew,

Module was working without issues, but suddenly from yesterday each time I run it I am getting following issue. Any idea?

Loading all objects. This can take a while on large tenants
Invoke-MgGraphRequest : The pipeline has been stopped.
At C:\Program Files\WindowsPowerShell\Scripts\get-windowsautopilotinfocommunity.ps1:1959 char:26
+ ... response = (Invoke-MgGraphRequest -Uri $url -Method Get -OutputType P ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-MgGraphRequest], PipelineStoppedException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest

Something went wrong. Error: Method not found: 'Void Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(Azure.Core.TokenCredential, System.String[], Microsoft.Kiota.Authentication.Azure.ObservabilityOptions, System.String[])'.
Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.
At D:\AutoPilot3.ps1:128 char:5
+     Stop-Transcript
+     ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Stop-Transcript], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.StopTranscriptCommand

**Comment by andrew-s-taylor** [comment]
Hi,
Can you confirm which version of the PowerShell SDK you have installed?
The module microsoft.graph.authentication is the best one to check

**Comment by Nikolara97** [comment]
Hey @andrew-s-taylor sorry for late response I was on vacation... After rolling back to older version of Graph.Authentification module everything work's again...

**Comment by secotton** [comment]
I'm having the same issue - been trying to get it working, but no avail.  Going to a different version of Graph.Authentication isn't quite helping, nor is using the updated one from Microsoft they released today (2.19.0).  What I've observed, is if I open a new PowerShell window, and re-run the get-windowsautopilotinfocommunity.ps1 script, it appears to function fine.  However - the kicker is I can't for the life of me get it to run within the context of a script.  It was all working great before Microsoft updated their Graph.Authentication module.

There's another post similar to this:   https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2715

**Comment by andrew-s-taylor** [comment]
Hi, is it any particular command in the module, or all of them?

**Comment by secotton** [comment]
So I'm running this during the OOBE portion of a Windows setup (Shift + F10).  I've got a PowerShell script that's hosted online that:
- sets the execution policy to bypassed
- installs NuGet
- Installs Microsoft.Graph (I've installed 2.17 since 2.18 seems to have an issue introduced)
- Installs / Imports the Az.KeyVault, Windows AutoPilot Info Community, and WindowsAutopilotIntuneCommunity module
- Connects to Azure AD (connect-azaccount)
- Gets the Autopilot parameters from a KeyVault
- Adds to the path:   $env:Path += ";C:\Program Files\WindowsPowerShell\Scripts"
- Kicks off the following:  get-windowsautopilotinfocommunity.ps1 -Online -AppId $AutopilotParams.AppId -AppSecret $AutopilotParams.secret -Tenantid $AutopilotParams.tenant -grouptag $GRPTAG

This is where the same error comes up.

Interestingly, if I run through this all manually, I get the same error. However, if I run Powershell from within a PowerShell window and re-run the same command ( get-windowsautopilotinfocommunity.ps1 -Online -AppId $AutopilotParams.AppId -AppSecret $AutopilotParams.secret -Tenantid $AutopilotParams.tenant -grouptag $GRPTAG ), it works as intended.

I tried also just specifying the -online parameter and used my own credentials, and same result.

Still working through the issues we saw came up last week around the time Microsoft updated the Graph module from 2.17 to 2.18.  I was hoping 2.19 would have fixed it, but it seems it didn't as of yet.

**Comment by andrew-s-taylor** [comment]
Ah, it's probably the AZ and Graph modules causing issues again, it happened with one of the V1 versions as well which broke pagination.

As a workaround, try adding "-newdevice" to the command, that skips retreiving the device list so won't worry about pagination issues

**Comment by secotton** [comment]
I've tried adding the "-newdevice" switch, and have the following error now:
Invoke-MgGraphRequest : The pipeline has been stopped.
At C:\Program Files\WindowsPowerShell\Scripts\get-windowsautopilotinfocommunity.ps1:639 char:17
+ ...             Invoke-MgGraphRequest -Uri $uri -Method Post -Body $json  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by secotton** [comment]
Before issuing the connect-azaccount, I had to issue:  Update-AzConfig -EnableLoginByWam $false

Seems to be working again now as intended.

**Comment by andrew-s-taylor** [comment]
Thank you for letting me know.  I'll add it as a comment in the next release :)

**Comment by andrew-s-taylor** [comment]
Hi, Is that the module, or the nuke script?
Looking at the error, it hasn't been passed the device ID

**Comment by jmullenhub** [comment]
This is from running the nuke script, all other pieces of the script are working except the delete intune device portion.

**Comment by andrew-s-taylor** [comment]
Does it list Intune devices before that?  It's not populating any device names in your yes/no message
